### ISSUE TITLE
Fails to build on macOS 

### ISSUE THREAD

**Issue by xavierhardy** [Ben-Xav/holycraap-front#11]
`fsevent`, a `react-scripts` dependency, is outdated and cannot be built on macOS. Upgrade the version of `react-scripts`.

**Comment by BenMorant** [comment]
I think it (and all my pain and sorrow) is because my nodejs version was itself outdated. now it should be fine. Please confirm :)

**Comment by BenMorant** [comment]
I add a similar 'problem' on GNU/LInux : 'fsevents' build as platform linux is not supported . But... As read here : "fsevents is an optional dependency (see: yarn.lock). It is only needed if you want to run LedgerSubprovider in a Node environment (which is not supported on Linux without additional build-dependent dependencies). You can safely ignore this warning."
